<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img__image-image  image-hand</name>
   <tag></tag>
   <elementGuidId>3afd56b1-6a9c-4d4f-a711-2a2119c6d115</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='mountRoot']/div/div/main/div/div[2]/div/div/div/div/div/div[2]/div/div/div/div/div/a/div/picture/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>image-image  image-hand</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://assets.myntassets.com/w_980,c_limit,fl_progressive,dpr_2.0/assets/images/2021/6/3/d2e0a562-e178-4024-96ea-6522cc2f1e8b1622735796695-Weekend-sale_DK-2.jpg</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mountRoot&quot;)/div[1]/div[@class=&quot;application-base&quot;]/main[@class=&quot;shop-base&quot;]/div[@class=&quot;myx-base&quot;]/div[@class=&quot;myx-indexContainer&quot;]/div[@class=&quot;myx-stretch&quot;]/div[@class=&quot;carousel-base&quot;]/div[@class=&quot;slick-initialized slick-slider&quot;]/div[@class=&quot;slick-list&quot;]/div[@class=&quot;slick-track&quot;]/div[@class=&quot;slick-slide slick-active slick-center carousel-slide&quot;]/div[@class=&quot;container-base myx-stretch&quot;]/div[1]/div[@class=&quot;container-container container-aspectContainer&quot;]/div[@class=&quot;row-base&quot;]/div[@class=&quot;column-base&quot;]/a[1]/div[1]/picture[@class=&quot;img-responsive&quot;]/img[@class=&quot;image-image  image-hand&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mountRoot']/div/div/main/div/div[2]/div/div/div/div/div/div[2]/div/div/div/div/div/a/div/picture/img</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://assets.myntassets.com/w_980,c_limit,fl_progressive,dpr_2.0/assets/images/2021/6/3/d2e0a562-e178-4024-96ea-6522cc2f1e8b1622735796695-Weekend-sale_DK-2.jpg')]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div/a/div/picture/img</value>
   </webElementXpaths>
</WebElementEntity>
